/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pii.v2;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.FileReader;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.toString;
public class DesempenhoFinalTela extends javax.swing.JFrame {

    /**
     * Creates new form DesempenhoFinalTela
     */
    public DesempenhoFinalTela() {
        super("Pontuação");
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CalcularButton1 = new javax.swing.JButton();
        parabensLabel1 = new javax.swing.JLabel();
        okButton1 = new javax.swing.JButton();
        desempenhoLabel1 = new javax.swing.JLabel();
        fundoLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CalcularButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        CalcularButton1.setText("Calcular Desempenho");
        CalcularButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        CalcularButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(CalcularButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 590, 560, 90));

        parabensLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        parabensLabel1.setText("Parabéns, você terminou!!");
        parabensLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        getContentPane().add(parabensLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 680, 180));

        okButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        okButton1.setText("Ok");
        okButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));
        okButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(okButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 910, 160, 70));

        desempenhoLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        desempenhoLabel1.setText("Sua nota aparecerá aqui!");
        desempenhoLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        getContentPane().add(desempenhoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, 560, 70));

        fundoLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FundoLogoS.jpg"))); // NOI18N
        fundoLabel1.setText("jLabel1");
        getContentPane().add(fundoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButton1ActionPerformed
        String h = desempenhoLabel1.getText();
        float nota = Float.parseFloat(h);
        if(nota >= 6){
            var it = new FinalBomTela();
            it.setVisible(true);
            dispose();
        }
        else{
            var it = new FinalRuimTela();
            it.setVisible(true);
            dispose();
        }       
        
    }//GEN-LAST:event_okButton1ActionPerformed

    private void CalcularButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularButton1ActionPerformed
        int total = 0, p = 1;
        String ra;       
        String linha;
        StringBuilder conteudo = new StringBuilder();
        try (BufferedReader br = new BufferedReader(new FileReader("login.txt"))) {
            while ((linha = br.readLine()) != null) {
                conteudo.append(linha);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
                
        ra = conteudo.toString();
        
        while(p <= 10){
            String file = String.format("q%d.txt",p);
            
            try(var fr = new FileReader(file)){
            int i;
            while((i = fr.read()) != -1){
                var o =(char)i;
                String h = String.valueOf(o);
                int g = Integer.parseInt(h);
                total += g;
                
            }
            }catch(IOException e){
                e.printStackTrace();
            }
            p++;      
        
        }
        
        float pontuacao = total/6; 
        desempenhoLabel1.setText(Float.toString(pontuacao));
        
        var dao = new DesempenhoDAO();
        var desempenho = new Desempenho(ra, pontuacao);
        try{
            dao.cadastrarDesempenho(desempenho);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_CalcularButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesempenhoFinalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesempenhoFinalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesempenhoFinalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesempenhoFinalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesempenhoFinalTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalcularButton1;
    private javax.swing.JLabel desempenhoLabel1;
    private javax.swing.JLabel fundoLabel1;
    private javax.swing.JButton okButton1;
    private javax.swing.JLabel parabensLabel1;
    // End of variables declaration//GEN-END:variables
}
