/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pii.v2;

import static com.mycompany.pii.v2.DesempenhoAdmTela.preencherTabela;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author wexle
 */
public class HubTelaAdm extends javax.swing.JFrame {

    /**
     * Creates new form HubTelaAdm
     */
    public HubTelaAdm() {
        super("Hub Adm");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desempenhoButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();
        fundoLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desempenhoButton.setText("<html> \t<font face=\"Comic Sans MS\" size = \"7\"> Desempenho</font> <br/> </html>");
        desempenhoButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        desempenhoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        desempenhoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desempenhoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(desempenhoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 560, 340, 120));

        sairButton.setText("<html> \t<font face=\"Comic Sans MS\" size = \"7\"> Sair</font> <br/> </html>");
        sairButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sairButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 730, 340, 120));

        fundoLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FundoLogo.png"))); // NOI18N
        fundoLabel1.setText("jLabel1");
        getContentPane().add(fundoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void desempenhoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desempenhoButtonActionPerformed
        var tela = new DesempenhoAdmTela();
        tela.setVisible(true);
                
        try {
            preencherTabela();
        } catch (Exception ex) {
            Logger.getLogger(DesempenhoAdmTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_desempenhoButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        var lt = new LoginTelaAdm();
        lt.setVisible(true);
        dispose();
    }//GEN-LAST:event_sairButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HubTelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HubTelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HubTelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HubTelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HubTelaAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton desempenhoButton;
    private javax.swing.JLabel fundoLabel1;
    private javax.swing.JButton sairButton;
    // End of variables declaration//GEN-END:variables
}
